sudo: required
services:
  - docker

before_install:
  - docker build -t pradsharma/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pradsharma/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-south-1-534190195211"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"